# Generated by Django 6.0.1 on 2026-01-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('material', 'size')},
        ),
    ]
