# Generated by Django 6.0.1 on 2026-01-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_variant_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('material', 'size', 'color')},
        ),
    ]
