# Generated by Django 6.0.1 on 2026-01-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_variant_unique_together_variant_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
